spring:

  datasource:
    url: jdbc:postgresql://postgres:5432/railway_db?options=-c%20TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    schema: public
    default-schema: public

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 3

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:railway-reservation-group}

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.soham.railway_reservation_engine.bookings.event
        spring.json.use.type.headers: true

    listener:
      ack-mode: record




jwt:
  secret: aGYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXphYmNkZWZnlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OTA=
  expiration: 86400000

razorpay:
  key-id: rzp_test_TNDBuagy1cIOMx
  key-secret: zCy0IQE7iwmt0CYg9d0kRK9w
  webhook-secret: 7S@ZvPxe8sU3dvi

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [correlationId=%X{correlationId}] [%thread] %logger{36} - %msg%n"