CREATE TABLE stations(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code VARCHAR(10) NOT NULL,
        name VARCHAR(100) NOT NULL,
        zone VARCHAR(50) NOT NULL,
        --Naming syntax for unique constraints which is having a constraint name
        CONSTRAINT unique_station_code UNIQUE (code)
);
