CREATE TABLE trains(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    number VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,

    CONSTRAINT unique_train_number UNIQUE (number),
    CONSTRAINT chk_train_type
                   CHECK(
                          type IN (
                                   'EXPRESS',
                                    'SUPERFAST',
                                   'RAJDHANI',
                                   'SHATABDI',
                                   'DURONTO',
                                   'PASSENGER'
                              )
                         )
);

