CREATE TABLE routes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    train_id BIGINT NOT NULL,
    station_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    arrival_time TIME ,
    departure_time TIME ,
    distance_km INT NOT NULL,

    CONSTRAINT fk_routes_train
        FOREIGN KEY (train_id)
            REFERENCES trains(id),

    CONSTRAINT fk_routes_station
        FOREIGN KEY (station_id)
            REFERENCES stations(id),

    --both train id and station id should be unique in the route table, as a train can stop at a station only once in its route
  CONSTRAINT unique_routes_train_station UNIQUE (train_id, station_id)
);