CREATE TABLE  coaches(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    train_id BIGINT NOT NULL,

    coach_number VARCHAR(10) NOT NULL,

    coach_type VARCHAR(30) NOT NULL,

    total_seats INT NOT NULL,

    CONSTRAINT fk_coaches_train FOREIGN KEY (train_id) REFERENCES trains(id),


    CONSTRAINT unique_coach_number_per_train UNIQUE (train_id, coach_number),
    CONSTRAINT chk_total_seats CHECK (total_seats > 0),
    CONSTRAINT chk_coach_type
                   CHECK(
                          coach_type IN (
                                   'SLEEPER',
                                    'AC_3_TIER',
                                   'AC_2_TIER',
                                   'AC_1_TIER',
                                   'GENERAL'
                              )
                         )
);
