CREATE TABLE seats(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    coach_id BIGINT NOT NULL,

    seat_number INT NOT NULL,

    berth_type VARCHAR(30) NOT NULL,

    CONSTRAINT fk_seats_coach FOREIGN KEY (coach_id) REFERENCES coaches(id),
    CONSTRAINT unique_seats_coach_number UNIQUE (coach_id, seat_number),
    CONSTRAINT chk_seats_number CHECK (seat_number > 0),

    CONSTRAINT chk_seats_berth_type
                   CHECK(
                          berth_type IN (
                                      'LOWER',
                                    'MIDDLE',
                                      'UPPER',
                                      'SIDE_LOWER',
                                      'SIDE_UPPER'
                              )
                         )
);