CREATE TABLE schedules
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    train_id BIGINT NOT NULL,

    journey_date DATE NOT NULL,

    status VARCHAR(20) NOT NULL,

    chart_prepared_at TIMESTAMP,

    CONSTRAINT pk_schedules
        PRIMARY KEY (id),

    CONSTRAINT fk_schedules_train
        FOREIGN KEY (train_id)
            REFERENCES trains(id),

    CONSTRAINT uk_schedules_train_date
        UNIQUE (train_id, journey_date),

    CONSTRAINT chk_schedules_status
        CHECK (
            status IN (
                       'OPEN',
                       'CLOSED',
                       'CHART_PREPARED'
                )
            )
);